workflows:
  android-workflow:
    name: ðŸ¤– Android workflow
    max_build_duration: 60
    environment:
      android_signing:
        - Treino Facil Key
      groups:
        - firebase_credentials
      vars:
        PACKAGE_NAME: "br.com.palmyro.treino_facil"
      flutter: 3.19.3
    inputs:
      version:
        description: â” Which version do you want to build?
        type: string
        default: "5.0.0"
      changelog:
        description: â” What's new in this version?
        type: string
        default: "Nothing new"
      environment:
        description: ðŸ§ª Selecione o ambiente que deseja gerar
        type: choice
        default: testing
        options:          
          - release
          - testing
    scripts:
      - name: âš’ï¸ Set up local.properties
        script: | 
            echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: ðŸ”Ž Get Flutter packages
        script: |
          flutter pub get
      - name: ðŸ“ˆ Load environment variables
        script: echo "GEMINI_API_KEY=${GEMINI_API_KEY}" > .env && echo "SENTRY_DNS=${SENTRY_DNS}" >> .env
      - name: ðŸ†• Generate release notes
        script: echo "${{ inputs.changelog }}" | tee release_notes.txt
      - name: ðŸ”¨ Build Android Version 
        script: |
          # Get the current date in YYYYMMDD format
          DATE=$(date +'%Y%m%d')
          LAST_TWO_DIGITS=$((RANDOM % 10))

          if [ ${{ inputs.environment }} == "release" ]; then
            # Calculate the version name and version number
            VERSION_NAME="${{ inputs.version }}"
            VERSION_NUMBER=${DATE}${LAST_TWO_DIGITS}
          else
            # Calculate the version name and version number
            VERSION_NAME="${{ inputs.version }}.${DATE}${LAST_TWO_DIGITS}"
            VERSION_NUMBER=${DATE}${LAST_TWO_DIGITS}
          fi
          
          # Print out the versions for debugging
          echo "Building ${{ inputs.environment }} version: $VERSION_NAME and version number: $VERSION_NUMBER"

          # Build the app bundle with the specified version name and version number
          flutter build appbundle --release --build-name="$VERSION_NAME" --build-number=$VERSION_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - gabripalmyro13579@gmail.com
        notify:
          success: true
          failure: false
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:
          app_id: 1:999959493758:android:77a1ae7e13b756b0da2c2f
          groups: 
            - android-testers