name: tabela_treino
description: A new Flutter project.

publish_to: 'none'

version: 3.1.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  provider: ^6.1.2
  brasil_fields: ^1.15.0
  mask_text_input_formatter: ^2.9.0
  auto_size_text: ^3.0.0
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  share_plus: ^10.0.0
  shared_preferences: ^2.0.18
  flutter_native_splash: ^2.4.0
  intl: ^0.19.0
  photo_view: ^0.15.0
  path_provider: ^2.1.4
  font_awesome_flutter: ^10.7.0
  flutter_animate: ^4.5.0
  google_generative_ai: ^0.4.4
  flutter_dotenv: ^5.1.0
  sentry_flutter: ^8.7.0
  
  #firebase dependecies
  firebase_storage: ^12.1.2
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  firebase_remote_config: ^5.0.4
  cloud_firestore: ^5.2.0
  firebase_analytics: ^11.2.1
  google_mobile_ads: ^4.0.0
  in_app_purchase: ^3.2.0
  
dev_dependencies:
  flutter_lints: ^4.0.0
  # flutter_test:
  #   sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path_android: "images/app_icon.png"
  image_path_ios: "images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
    - shorebird.yaml

  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/GothamMedium.ttf
        - asset: assets/fonts/GothamMediumItalic.ttf
          style: italic
    - family: GothamBold
      fonts:
        - asset: assets/fonts/GothamBold.ttf
        - asset: assets/fonts/GothamBoldItalic.ttf
    - family: GothamBook
      fonts:
        - asset: assets/fonts/GothamBook.ttf
        - asset: assets/fonts/GothamBookItalic.ttf
    - family: GothamLight
      fonts:
        - asset: assets/fonts/GothamLight.ttf
    - family: GothamThin
      fonts:
        - asset: assets/fonts/Gotham-Thin.otf
  