// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAxHgpKuephg-Wo6rqDUnYI0ZOrHX8Sf4',
    appId: '1:999959493758:android:77a1ae7e13b756b0da2c2f',
    messagingSenderId: '999959493758',
    projectId: 'treino-facil-22856',
    storageBucket: 'treino-facil-22856.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ0A7YjK8wBzBQsFBBQqQqKoHWQqvTvOQ',
    appId: '1:999959493758:ios:bfed6e131f7a07c8da2c2f',
    messagingSenderId: '999959493758',
    projectId: 'treino-facil-22856',
    storageBucket: 'treino-facil-22856.appspot.com',
    androidClientId: '999959493758-t0iubl0fofbqq1lnlphra477cpc0ftj0.apps.googleusercontent.com',
    iosClientId: '999959493758-eoeb0km9pis1ijvjjndufs6aif6hgmuc.apps.googleusercontent.com',
    iosBundleId: 'br.com.palmyro.treinofacil.treinoFacil',
  );
}
